### PR TITLE
Fix #45. Move nyan-animation-timer control into nyan-mode function.

### LINKED ISSUE #45: Disabling nyan-mode leaves an expensive timer running
I noticed that Emacs was hitting my CPU pretty heavily and traced the problem back to a lingering nyan-animation-timer that was spinning despite my having disabled nyan-mode.

## Steps to reproduce
Emacs version 26.3, nyan-mode 1.1.2

1. Start up top, or your favorite CPU monitor.
2. Start emacs -Q -l nyan-mode.el
3. M-x nyan-mode
4. Watch the emacs process use some CPU but quiet down to minimal usage (basically nothing on my laptop, just a few spikes every now and then).
5. Evaluate (customize-set-variable 'nyan-animate-nyancat t)
6. Watch the emacs process start consuming CPU.  >3% on my laptop, though up to way more if I enable other heavyweight mode line constructs.
7. M-x nyan-mode (disable nyan-mode)
8. Watch the emacs process continue to consume CPU.  >2% on my laptop, though still a lot if I enable other mode line constructs.
9. M-x nyan-stop-animation
10. Watch the process go back down to minimal CPU usage.

## Expected behavior 
CPU usage should stop when disabling nyan-mode.

## Analysis 
After step (9) above, M-x list-timers shows that the nyan-animation-timer is still spinning.  This forces an expensive mode-line update every second.  The problem is that the timer only gets canceled through customizing nyan-animate-nyancat, not through disabling the actual mode.

### PR DESCRIPTION
**Pull request by tmurph**

### CODE REVIEW

**Comment by Zulu-Inuoe** [comment]
Hey @TeMPOraL ! Any chance of merging this in? I just noticed this behaviour this morning and was about to open an issue and fork to PR, but it looks like @tmurph 's already done that work.

**Comment by damon-kwok** [comment]
@TeMpOraL
This change is estimated that countless users get an emacs startup error:
````
Symbol's function definition is void: nyan-start-animation.
````
You can use obsolete functions. See:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Obsolete-Functions.html

Or
````elisp
(defun nyan-start-animation() (message "nyan-start-animation is obsolete!")
````

**Comment by TeMPOraL** [comment]
Sorry. Didn't test it as thoroughly as I should have. Will fix in a moment.

**Comment by TeMPOraL** [comment]
Should  be resolved now.

**Comment by Zulu-Inuoe** [comment]
Thank you!
I'm sorry, I should have done my part in reviewing the changes rather than taking them for granted.

**Comment by TeMPOraL** [comment]
You're welcome!
Don't worry. I should've tested before merging code in. Thanks @damon-kwok for reporting my mistake to me immediately, before a lot of people lost their favourite cat!

**Pull request merged**
