### PR TITLE
Added music

### PR DESCRIPTION
**Pull request by folone**
I only found one way to play music looped and asynchronously[1].
Therefore, mplayer[2] needs to be installed in the system.

[1]: http://www.emacswiki.org/emacs/ErcSound#toc4
[2]: http://www.mplayerhq.hu/

### CODE REVIEW

**Comment by amagura** [comment]
@folone couldn't you make it so that the music could still be added while leaving it out?  As in, add support for users to specify an mp3 file.

That way users who have bought a copy of the song, or whatever, could still take advantage of it while still protecting nyan-mode in-case somebody did use it without permission. (Assuming @TeMPOraL is fine with that)

I think this is sorta what playstation emulators do: they provide the emulation, but _not_ the bios necessary for the emulation to run, thus leaving the liability up to the end-user: it's legal to own a copy of the bios, I believe, if you own the system using said bios: playstation 2 for playstation 2 bios.

**Comment by folone** [comment]
@amagura according to wikipedia, the whole nyan-cat character is copyrighted, with patents pending for the name "nyan cat". This includes the image, the music, and the original video. This mode already infringes on those copyrights. The copyright holders don't seem to be interested in exercising their rights if the character is not used commercially though.

**Comment by amagura** [comment]
@folone, sounds edgy.  

It says nothing about the music, though?  I mean, whether he cares about it being used commercially or not?  Also, at this point, I think it would be pointless to try to make people not use the character and the name since a handful of projects already use it.

**Comment by TeMPOraL** [comment]
I guess we can always revert if something goes wrong.

**Pull request merged**
